config/routes.rb
Rails.application.routes.draw do
  
 
  resources :bloggers
  get 'support/aboutus'
  get 'support/help'
  get 'support/contact'
  get 'support/offer'
  get 'support/pricing'
  get 'support/blog'
  get 'support/confirm'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landing/index'
  get 'landing/devel'
  get 'landing/three'
  get 'landing/test'

  get 'store/intelligence'
  get 'store/bloggers'

  resources :orders
  resources :line_items, only: [:new, :create, :edit, :update, :destroy]
  resources :carts do
    resources :line_items
  end

  get 'store/index' => 'store#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :admin do
     resources :products do
      resources :images
    end
  end
  
  resources :users do
    resources :products do
      resources :images
    end
  end

  resources :styles, only: [:new, :create, :edit, :update, :destroy] do
    resources :genders, only: [:new, :create, :edit, :update, :destroy] do
      resources :sizes, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :images
  resources :store, :controller => "products"

  

  root 'store#index' 

  get ':id' => 'products#show'
  get 'blogger/index' => 'landing#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	accepts_nested_attributes_for :line_items, :reject_if => lambda { |t| t['line_item'].nil? }

	def add_product(product_id, size_id, color_id)
	    current_item = line_items.find_by(product_id: product_id, size_id: size_id, color_id: color_id)
	    if current_item
	         current_item.quantity += 1
	    else
	         current_item = line_items.build(product_id: product_id, size_id: size_id, color_id: color_id)
	    end
	    current_item
 	end

  	def total_price
     	line_items.to_a.sum { |item| item.total_price }
  	end
  	def total_count
     	line_items.to_a.sum { |item| item.total_count }
  	end
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :products
		has_many :line_items
	
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	has_many :orders
end

app/models/gender.rb
class Gender < ActiveRecord::Base

end

app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :product
	has_attached_file :photo, :styles => { :medium => "470x627#", :thumb => "220x293#" }
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	validates_attachment :photo, presence: true
	

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  belongs_to :size
  belongs_to :color

  def total_price
    product.price * quantity
  end
  def total_count
    quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_many :products, through: :line_items
	belongs_to :delivery
	validates :name, :address, :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	

	def add_line_items_from_cart(cart)
         cart.line_items.each do |item|
             item.cart_id = nil
             line_items << item
		end
	end
	def order_count
		line_items.to_a.sum { |item| item.quantity}
	end
	def order_sum
		line_items.to_a.sum { |item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :url_name
	belongs_to :style
	has_many :images, dependent: :destroy, :autosave => true
	has_many :line_items

	has_many :orders, through: :line_items
	has_many :colors, through: :product_colors
	has_many :product_colors
	before_destroy :ensure_not_referenced_by_any_line_item
	belongs_to :user
	accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }
	validates :title, :url_name, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.10}
	validates :title, uniqueness: true
	validates :url_name, uniqueness: true, format: { with: /\A[_a-z]+\z/, message: 'только строчные буквы' }

	def item_count
		orders.to_a.sum { |item| item.order_count}
	end

	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end	
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
	belongs_to :product
	belongs_to :color
end

app/models/size.rb
class Size < ActiveRecord::Base

	belongs_to :style
	has_many :line_items
	
end

app/models/sizetable.rb
class Sizetable < ActiveRecord::Base
	belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :products
  has_many :sizetables
  has_many :sizes
  has_many :colors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  accepts_nested_attributes_for :products, :reject_if => lambda { |t| t['product'].nil? }
  has_many :orders
  accepts_nested_attributes_for :orders, :reject_if => lambda { |t| t['product'].nil? }
  

end

app/controllers/bloggers_controller.rb
class BloggersController < InheritedResources::Base

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end
    # POST /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)



    respond_to do |format|
      if @blogger.save
        format.html { redirect_to :back }
        
        format.json { render :show, status: :created, location: @blogger }
      else
        format.html { render :new }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /bloggers/1
  # DELETE /bloggers/1.json
  def destroy
    @blogger.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format js
      format.json { head :no_content }
    end
  end



  private

    def blogger_params
      params.require(:blogger).permit(:name, :tel, :account)
    end
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/bloggers/_form.html.erb
<%= form_for(@blogger, class: "nobottommargin", id: "template-contactform") do |f| %>
  <% if @blogger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
      <% @blogger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-process"></div>

  <div class="col_half" >

    <%= f.text_field :name, class: "sm-form-control border-form-control required", id: "template-contactform-name", placeholder: "Имя", :required => true  %>
  </div>
  <div class="col_half col_last">

    <%= f.text_field :tel, class: "sm-form-control border-form-control required", id: "template-contactform-name", placeholder: "+7 909 9090 90 90", :required => true, :pattern =>  "^([0|\+[0-9]{1,5})?([1-9][0-9]{9})$" %>
  </div>
  <div class="col_full">

    <%= f.text_field :account, class: "sm-form-control border-form-control required", id: "template-contactform-name", placeholder: "Ваш аккаунт, например: @kyliejenner", :required => true %>
  </div>
  <div class="col_full center">
    <%= f.submit 'Отправить', class: "button button-border button-circle t500 noleftmargin topmargin-sm", id: "template-contactform-submit" %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing Blogger</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogger %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tel</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggers.each do |blogger| %>
      <tr>
        <td><%= blogger.name %></td>
        <td><%= blogger.tel %></td>
        <td><%= blogger.account %></td>
        <td><%= link_to 'Show', blogger %></td>
        <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
        <td><%= link_to 'Destroy', blogger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogger', new_blogger_path %>

app/views/bloggers/new.html.erb
<h1>New Blogger</h1>

<%= render 'form' %>

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blogger.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @blogger.tel %>
</p>

<p>
  <strong>Account:</strong>
  <%= @blogger.account %>
</p>

<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>