config/routes.rb
Rails.application.routes.draw do
  
 
  resources :bloggers
  get 'support/aboutus'
  get 'support/help'
  get 'support/contact'
  get 'support/offer'
  get 'support/pricing'
  get 'support/blog'
  get 'support/confirm'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landing/index'
  get 'landing/devel'
  get 'landing/three'
  get 'landing/test'

  get 'store/intelligence'
  get 'store/bloggers'

  resources :orders
  resources :line_items, only: [:new, :create, :edit, :update, :destroy]
  resources :carts do
    resources :line_items
  end

  get 'store/index' => 'store#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :admin do
     resources :products do
      resources :images
    end
  end
  
  resources :users do
    resources :products do
      resources :images
    end
  end

  resources :styles, only: [:new, :create, :edit, :update, :destroy] do
    resources :genders, only: [:new, :create, :edit, :update, :destroy] do
      resources :sizes, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :images
  resources :store, :controller => "products"

  

  root 'store#index' 

  get ':id' => 'products#show'
  get 'blogger/index' => 'landing#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	accepts_nested_attributes_for :line_items, :reject_if => lambda { |t| t['line_item'].nil? }

	def add_product(product_id, size_id, color_id)
	    current_item = line_items.find_by(product_id: product_id, size_id: size_id, color_id: color_id)
	    if current_item
	         current_item.quantity += 1
	    else
	         current_item = line_items.build(product_id: product_id, size_id: size_id, color_id: color_id)
	    end
	    current_item
 	end

  	def total_price
     	line_items.to_a.sum { |item| item.total_price }
  	end
  	def total_count
     	line_items.to_a.sum { |item| item.total_count }
  	end
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :products
		has_many :line_items
	
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	has_many :orders
end

app/models/gender.rb
class Gender < ActiveRecord::Base

end

app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :product
	has_attached_file :photo, :styles => { :medium => "470x627#", :thumb => "220x293#" }
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	validates_attachment :photo, presence: true
	

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  belongs_to :size
  belongs_to :color

  def total_price
    product.price * quantity
  end
  def total_count
    quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_many :products, through: :line_items
	belongs_to :delivery
	validates :name, :address, :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	

	def add_line_items_from_cart(cart)
         cart.line_items.each do |item|
             item.cart_id = nil
             line_items << item
		end
	end
	def order_count
		line_items.to_a.sum { |item| item.quantity}
	end
	def order_sum
		line_items.to_a.sum { |item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :url_name
	belongs_to :style
	has_many :images, dependent: :destroy, :autosave => true
	has_many :line_items

	has_many :orders, through: :line_items
	has_many :colors, through: :product_colors
	has_many :product_colors
	before_destroy :ensure_not_referenced_by_any_line_item
	belongs_to :user
	accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }
	validates :title, :url_name, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.10}
	validates :title, uniqueness: true
	validates :url_name, uniqueness: true, format: { with: /\A[_a-z]+\z/, message: 'только строчные буквы' }

	def item_count
		orders.to_a.sum { |item| item.order_count}
	end

	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end	
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
	belongs_to :product
	belongs_to :color
end

app/models/size.rb
class Size < ActiveRecord::Base

	belongs_to :style
	has_many :line_items
	
end

app/models/sizetable.rb
class Sizetable < ActiveRecord::Base
	belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :products
  has_many :sizetables
  has_many :sizes
  has_many :colors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  accepts_nested_attributes_for :products, :reject_if => lambda { |t| t['product'].nil? }
  has_many :orders
  accepts_nested_attributes_for :orders, :reject_if => lambda { |t| t['product'].nil? }
  

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  include CurrentCart
  before_action :set_cart
  layout :resolve_layout
  
  def index
  	@product = Product.all
    set_meta_tags title: 'Создать собственный дизайн футболок, свитшотов, толстовок и худи',
                  description: 'Создать и начать продавать футболки, свитшоты, толстовки и худи с уникальным дизайном без вложений',
                  keywords: 'создать футболку с принтом, без вложений, начать продавать, футболка, толстовка, свитшот, худи, с принтами, дизайн, блоггер, создать, купить'

  end

  def three
    set_meta_tags title: 'Купить или создать футболки, свитшоты, толстовки и худи',
                  description: 'Купить или создать и начать продавать футболки, свитшоты, толстовки и худи с уникальным дизайном без вложений',
                  keywords: 'футболки с принтами, толстовки с принтами, футболка, толстовка, свитшот, худи, с принтами, дизайн, блоггер, создать, купить',
                  og: {
                    image: url_for('sound.jpg')
                  }
  end
   def devel
  end

  private

  def resolve_layout
    case action_name
    when "index"
      "application"
    else 
      "landdev"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/landing/devel.html.erb
<div class="row " style="min-height:100vh;">
	<div class="small-6 large-centered columns text-center" >
		<br>
		<br>
		<br>		<br>
		<br>
		<br>

		<%= image_tag 'logo.png', size:"174x68", class: "float-center" %>
		<br>
		<br>
		<br>
		<h4> Наш сайт трансформируется, подождите немножко</h4>

	</div>
</div>

app/views/landing/index.html.erb
<% content_for :title, "Создать собственный дизайн футболок, свитшотов, толстовок и худи" %>   
 <!-- Hero секция -->

<section class="hero1">


  <div class="row">
    <div class="large-6 large-push-0 columns" style="padding-top: 5vh; ">
      <div class="circle-bg quote-1">
        <p style="font-size:20px;">Мы знаем, что у Вас<br>миллион идей.</p>
      </div>
    </div>
    <div class="large-6 large-pull-0 columns" >
      <div class="circle-bg quote-2">
        <p style="font-size:20px;">Часть из них мы поможем реализовать.</p>
      </div>
    </div>
  </div>



</section>

<div class="row text-center hero2">
  <div class="small-12 columns">
    <h2>Мы поможем создать собственную одежду.</h2>
    <h2 class="subheader">  </h2>
  </div>
</div>

 



<hr>
 <!-- разделитель -->
<div class="row">
<h2 class="subheader text-center">Как с нами работать</h2>
</div>

<section class="benefits">
  <div class="row">
    <div class="small-12 large-4 columns benefit">
      <i class="fi-star icon"></i>
      <h5> Создайте свой собственный дизайн </h5>
      <hr>
      <p> Мы поможем вам разместить его на одном из наших продуктов. </p>
    </div>
    <div class="small-12 large-4 columns benefit">
      <i class="fi-shopping-cart icon"></i>
      <h5> Закажите образец для себя и не забудьте сделать фото для своей аудитории. </h5>
      <hr>
      <p> Мы произведем и отправим вам ваше собственное изделие, чтобы вы могли сами убедиться в его качестве перед тем как советовать его тем, кто вас любит. </p>
    </div>
    <div class="small-12 large-4 columns benefit">
      <i class="fi-upload-cloud icon"></i>
      <h5> Создайте в своем кабинет коллаборацию и загрузите туда фото. </h5>
      <hr>
      <p> Это займет у вас не более 5 минут, после чего ваш товар появится у нас на сайте и станет доступным для заказа. </p>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-4 columns benefit">
      <i class="fi-trophy icon"></i>
      <h5> Все готово, следите за продажами. </h5>
      <hr>
      <p> В личном кабинете у Вас будет возможность следить за заказами, что поможет вам понять когда лучше выкладывать новое фото.  </p>
    </div>
    <div class="small-12 large-4 columns benefit">
      <i class="fi-credit-card icon"></i>
      <h5> Загрузите свои банковские реквизиты и получайте прибыль.</h5>
      <hr>
      <p> Загрузите свои банковские реквизиты и запросите перевод прибыли тогда, когда посчитаете нужным. С условиями начисления прибыли можно ознакомиться <%= link_to 'здесь', support_offer_path, class: "lead" %>. </p>
    </div>
    <div class="small-12 large-4 columns benefit">
      <i class="fi-torsos-all icon"></i>
      <h5> Становитесь нашими партнерами. </h5>
      <hr>
      <p> Для наших постоянных партнеров у нас индивидуальных подход, доступ к экспериментальным моделям, а также специальные условия сотрудничества. </p>
    </div>
  </div>
</section>
<br>

 <!-- разделитель -->
<div class="row">
<h2 class="subheader text-center">Наши продукты, на которые Вы можете нанести свой дизайн</h2>
</div>
 <!-- наши болванки -->
    
    <div class="row">
      <div class="medium-4 columns">
        <div class="profile-card">
          <%= image_tag 'hoody_haki.png' %>
          
          <div class="profile-info">
            <h3 class="subheader">Худи</h3>
               <p>85%хлопок, 15% пэ<br>Необычный крой с рельефами и внутренними карманами.<br>Цвета: чёрный, белый, хаки, бордовый.<br>Фасон: унисекс.<br></p>
            <p><%= link_to 'Узнать больше', store_path(@product.first.id) %> | <%= link_to 'Пример', store_path(@product.second.id) %> </p>

          </div>
        </div>
      </div>

      <div class="medium-4 columns">
        <div class="profile-card">
          <%= image_tag 'swshred.png' %>
          <div class="profile-info">
            <h3 class="subheader">Свитшот Basic</h3>
               <p>85%хлопок, 15% пэ<br>Базовая модель из утеплённого хлопка.<br>Цвета: чёрный, белый, хаки, бордовый.<br>Фасон: унисекс.<br></p>
            <p><%= link_to 'Узнать больше', store_path(@product.first.id) %> | <%= link_to 'Пример', store_path(@product.second.id) %> </p>
            
            </ul>
          </div>
        </div>
      </div>
    </div>
 <!-- футболки 
    <div class="row">



      <div class="medium-4 columns">
        <div class="profile-card">
          <%= image_tag 'cropshot.png' %>
          <div class="profile-info">
          <h3 class="subheader">Кропшот</h3>
            <p>85%хлопок, 15% пэ<br>Толстовка для дома, спорта, отдыха.<br>Свободный крой, классно смотрится с топом.<br>Цвета: чёрный, белый, хаки, бордовый.<br>Размер: onesize.<br></p>
            <p><%= link_to 'Узнать больше', store_path(@product.first.id) %> | <%= link_to 'Пример', store_path(@product.second.id) %> </p>

          </div>
        </div>
      </div>


            <div class="medium-4 columns">
        <div class="profile-card">
          <%= image_tag 'mockup_hoody.png' %>
          
          <div class="profile-info">
            <h3 class="subheader">Футболка Basic</h3>
            <p>100% хлопок<br>Современный крой, сидит отлично на любой фигуре.<br>Цвета: чёрный, белый.<br>Фасон: мужской, женский.<br></p>
            <p><%= link_to 'Узнать больше', store_path(@product.first.id) %> | <%= link_to 'Пример', store_path(@product.second.id) %> </p>

          </div>
        </div>
      </div>
      <div class="medium-4 columns">
        <div class="profile-card">
          <%= image_tag 'mockup_hoody.png' %>
          <div class="profile-info">
          <h3 class="subheader">Футболка Oversized</h3>
            <p>100% хлопок<br>Крой очень свободный.<br>Цвета: чёрный.<br>Фасон: унисекс.<br></p>
            <p><%= link_to 'Узнать больше', store_path(@product.first.id) %> | <%= link_to 'Пример', store_path(@product.second.id) %> </p>

          </div>
        </div>
      </div>

-->









    </div>

app/views/landing/three.html.erb
<% content_for :title, "Купить или создать футболки, свитшоты, толстовки и худи" %>   
<div class="row menu_container" style="font-family: 'Playfair Display SC', serif;">
	<div class="large-10 medium-12 small-12 large-centered text-left column menu_three blog">
		<%= link_to 'ДЛЯ БЛОГГЕРОВ', blogger_index_path%>
	</div>
	<div class="large-10 medium-12 small-12 large-centered text-left column menu_three store">
		<%= link_to 'ДЛЯ ПОКУПАТЕЛЕЙ', store_index_path%>
	</div>
	<div class="large-10 medium-12 small-12 large-centered text-left column menu_three individ">
		<%= link_to ('ИНДИВИДУАЛЬНЫЕ<br>ЗАКАЗЫ').html_safe, support_blog_path %>
	</div>
	<div class="column">
	</div>
</div>