config/routes.rb
Rails.application.routes.draw do
  
 
  resources :bloggers
  get 'support/aboutus'
  get 'support/help'
  get 'support/contact'
  get 'support/offer'
  get 'support/pricing'
  get 'support/blog'
  get 'support/confirm'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landing/index'
  get 'landing/devel'
  get 'landing/three'
  get 'landing/test'

  get 'store/intelligence'
  get 'store/bloggers'

  resources :orders
  resources :line_items, only: [:new, :create, :edit, :update, :destroy]
  resources :carts do
    resources :line_items
  end

  get 'store/index' => 'store#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :admin do
     resources :products do
      resources :images
    end
  end
  
  resources :users do
    resources :products do
      resources :images
    end
  end

  resources :styles, only: [:new, :create, :edit, :update, :destroy] do
    resources :genders, only: [:new, :create, :edit, :update, :destroy] do
      resources :sizes, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :images
  resources :store, :controller => "products"

  

  root 'store#index' 

  get ':id' => 'products#show'
  get 'blogger/index' => 'landing#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	accepts_nested_attributes_for :line_items, :reject_if => lambda { |t| t['line_item'].nil? }

	def add_product(product_id, size_id, color_id)
	    current_item = line_items.find_by(product_id: product_id, size_id: size_id, color_id: color_id)
	    if current_item
	         current_item.quantity += 1
	    else
	         current_item = line_items.build(product_id: product_id, size_id: size_id, color_id: color_id)
	    end
	    current_item
 	end

  	def total_price
     	line_items.to_a.sum { |item| item.total_price }
  	end
  	def total_count
     	line_items.to_a.sum { |item| item.total_count }
  	end
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :products
		has_many :line_items
	
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	has_many :orders
end

app/models/gender.rb
class Gender < ActiveRecord::Base

end

app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :product
	has_attached_file :photo, :styles => { :medium => "470x627#", :thumb => "220x293#" }
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	validates_attachment :photo, presence: true
	

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  belongs_to :size
  belongs_to :color

  def total_price
    product.price * quantity
  end
  def total_count
    quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_many :products, through: :line_items
	belongs_to :delivery
	validates :name, :address, :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	

	def add_line_items_from_cart(cart)
         cart.line_items.each do |item|
             item.cart_id = nil
             line_items << item
		end
	end
	def order_count
		line_items.to_a.sum { |item| item.quantity}
	end
	def order_sum
		line_items.to_a.sum { |item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :url_name
	belongs_to :style
	has_many :images, dependent: :destroy, :autosave => true
	has_many :line_items

	has_many :orders, through: :line_items
	has_many :colors, through: :product_colors
	has_many :product_colors
	before_destroy :ensure_not_referenced_by_any_line_item
	belongs_to :user
	accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }
	validates :title, :url_name, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.10}
	validates :title, uniqueness: true
	validates :url_name, uniqueness: true, format: { with: /\A[_a-z]+\z/, message: 'только строчные буквы' }

	def item_count
		orders.to_a.sum { |item| item.order_count}
	end

	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end	
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
	belongs_to :product
	belongs_to :color
end

app/models/size.rb
class Size < ActiveRecord::Base

	belongs_to :style
	has_many :line_items
	
end

app/models/sizetable.rb
class Sizetable < ActiveRecord::Base
	belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :products
  has_many :sizetables
  has_many :sizes
  has_many :colors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  accepts_nested_attributes_for :products, :reject_if => lambda { |t| t['product'].nil? }
  has_many :orders
  accepts_nested_attributes_for :orders, :reject_if => lambda { |t| t['product'].nil? }
  

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  respond_to :html, :js
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @size = Size.find(params[:size_id])
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create

    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id, params[:size_id], params[:color_id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to :back }
        format.js 
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    @cart = Cart.find(session[:cart_id])
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :size_id, :color_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
                <tr class="cart_item">
                  <td class="cart-product-remove">
                    <%= link_to line_item_path(line_item.id), :method => :delete, class: "remove" do %><i class="icon-trash2"></i><% end %>
                  </td>

                  <td class="cart-product-thumbnail">
                    <a href="#"><% if line_item.product.images.present? %><%= image_tag line_item.product.images.first.photo(:thumb), size: "64x64" %> <% end %></a>
                  </td>

                  <td class="cart-product-name">
                    <a href="#"><%= line_item.product.title %> <br> <%= line_item.size.name %></a>
                  </td>

                  <td class="cart-product-price">
                    <span class="amount"><%= line_item.product.price %> руб.</span>
                  </td>

                  <td class="cart-product-quantity">
                    <div class="quantity clearfix">
                      <input type="button" value="-" class="minus">
                      <input type="text" name="quantity" value="2" class="qty" />
                      <input type="button" value="+" class="plus">
                    </div>
                  </td>

                  <td class="cart-product-subtotal">
                    <span class="amount"><%= line_item.total_price %></span>
                  </td>
                </tr>
                




 

app/views/line_items/_line_item_order.html.erb
     <tbody>
     <tr>

	
		<td ><%= line_item.product.title %></td>
		<td ><%= line_item.product.style.name %></td>
		<td ><%= line_item.size.name %></td>	
		<td ><%= line_item.quantity %>&times; </td>
		<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
		<td >
			<button >
			
				<span aria-hidden="true"><%= link_to '&times;'.html_safe, line_item_path(line_item.id), :method => :delete, id: "delete" %></span>
	    	</button>
	    </td>
     </tr>
 

app/views/line_items/create.js.erb
$('#cart_count').html("<%= escape_javascript render('layouts/cart_count') %>");
$('#cart-items').html("<%= escape_javascript render('layouts/cart_items') %>");
$('#cart-total').html("<%= escape_javascript render('layouts/cart_total') %>");

app/views/line_items/destroy.js.erb
$('#cart_count').html("<%= escape_javascript render('layouts/cart_count') %>");
$('#cart-items').html("<%= escape_javascript render('layouts/cart_items') %>");
$('#cart-total').html("<%= escape_javascript render('layouts/cart_total') %>");

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>