config/routes.rb
Rails.application.routes.draw do
  
 
  resources :bloggers
  get 'support/aboutus'
  get 'support/help'
  get 'support/contact'
  get 'support/offer'
  get 'support/pricing'
  get 'support/blog'
  get 'support/confirm'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landing/index'
  get 'landing/devel'
  get 'landing/three'
  get 'landing/test'

  get 'store/intelligence'
  get 'store/bloggers'

  resources :orders
  resources :line_items, only: [:new, :create, :edit, :update, :destroy]
  resources :carts do
    resources :line_items
  end

  get 'store/index' => 'store#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :admin do
     resources :products do
      resources :images
    end
  end
  
  resources :users do
    resources :products do
      resources :images
    end
  end

  resources :styles, only: [:new, :create, :edit, :update, :destroy] do
    resources :genders, only: [:new, :create, :edit, :update, :destroy] do
      resources :sizes, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :images
  resources :store, :controller => "products"

  

  root 'store#index' 

  get ':id' => 'products#show'
  get 'blogger/index' => 'landing#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	accepts_nested_attributes_for :line_items, :reject_if => lambda { |t| t['line_item'].nil? }

	def add_product(product_id, size_id, color_id)
	    current_item = line_items.find_by(product_id: product_id, size_id: size_id, color_id: color_id)
	    if current_item
	         current_item.quantity += 1
	    else
	         current_item = line_items.build(product_id: product_id, size_id: size_id, color_id: color_id)
	    end
	    current_item
 	end

  	def total_price
     	line_items.to_a.sum { |item| item.total_price }
  	end
  	def total_count
     	line_items.to_a.sum { |item| item.total_count }
  	end
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :products
		has_many :line_items
	
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	has_many :orders
end

app/models/gender.rb
class Gender < ActiveRecord::Base

end

app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :product
	has_attached_file :photo, :styles => { :medium => "470x627#", :thumb => "220x293#" }
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	validates_attachment :photo, presence: true
	

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  belongs_to :size
  belongs_to :color

  def total_price
    product.price * quantity
  end
  def total_count
    quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_many :products, through: :line_items
	belongs_to :delivery
	validates :name, :address, :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	

	def add_line_items_from_cart(cart)
         cart.line_items.each do |item|
             item.cart_id = nil
             line_items << item
		end
	end
	def order_count
		line_items.to_a.sum { |item| item.quantity}
	end
	def order_sum
		line_items.to_a.sum { |item| item.total_price}
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :url_name
	belongs_to :style
	has_many :images, dependent: :destroy, :autosave => true
	has_many :line_items

	has_many :orders, through: :line_items
	has_many :colors, through: :product_colors
	has_many :product_colors
	before_destroy :ensure_not_referenced_by_any_line_item
	belongs_to :user
	accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }
	validates :title, :url_name, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.10}
	validates :title, uniqueness: true
	validates :url_name, uniqueness: true, format: { with: /\A[_a-z]+\z/, message: 'только строчные буквы' }

	def item_count
		orders.to_a.sum { |item| item.order_count}
	end

	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end	
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
	belongs_to :product
	belongs_to :color
end

app/models/size.rb
class Size < ActiveRecord::Base

	belongs_to :style
	has_many :line_items
	
end

app/models/sizetable.rb
class Sizetable < ActiveRecord::Base
	belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :products
  has_many :sizetables
  has_many :sizes
  has_many :colors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  accepts_nested_attributes_for :products, :reject_if => lambda { |t| t['product'].nil? }
  has_many :orders
  accepts_nested_attributes_for :orders, :reject_if => lambda { |t| t['product'].nil? }
  

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="container clearfix">
	  <div class="nobottommargin clearfix">
	    <%is_alert = alert.present? ? "alert" : ""%>
	      <div data-alert class="style-msg <%=is_alert%>">
	        <%=notice || alert%>
	        <a href="#" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
	      </div>
	  </div>
  </div>
<%end%>

app/views/layouts/_cart_count.html.erb
      <%=@cart.total_count%>

app/views/layouts/_cart_items.html.erb
                 <% @cart.line_items.each do |line_item| %>
                  <div class="top-cart-item clearfix">

                    <div class="top-cart-item-image">
                      <a href="#"><%= image_tag line_item.product.images.first.photo(:thumb) %></a>
                    </div>
                    
                    <div class="top-cart-item-desc">
                      <a href="#"><%= line_item.product.title %></a>
                      <span class="top-cart-item-price"><%= line_item.size.name %><br><%= line_item.total_price %> руб.</span>
                      <span class="top-cart-item-quantity">x <%= line_item.total_count %><br><br><%= link_to line_item_path(line_item.id), remote:true, :method => :delete,  class: "remove" do %><i class="icon-trash2"></i><% end %></span>
                    </div>

                  </div>
                   <% end %> 

app/views/layouts/_cart_total.html.erb
<%= @cart.total_price %> руб.

app/views/layouts/_footer.html.erb
    <!-- Footer
    ============================================= -->
    <footer id="footer" class="dark">

      <div class="container">

        <!-- Footer Widgets
        ============================================= -->
        <div class="footer-widgets-wrap clearfix">

          <div class="col_two_third">

            <div class="col_one_third">

              <div class="widget clearfix">

                

                <p>Создаем чуть <strong>больше</strong> <strong>возможностей</strong> для творчества </p>

                <div style="background: url(<%= asset_url 'world-map.png' %>) no-repeat center center; background-size: 100%;">
                  <address>
                    <strong></strong><br>
                   Трехгорная мануфактура, ул. Рочдельская 15, к. 17-18<br>
                    <br>
                  </address>
                  <abbr title="Phone Number"><strong>Телефон:</strong></abbr> +7-925-704-01-81<br>
                  <abbr title="Fax"><strong></strong></abbr> 
                  <abbr title="Email Address"><strong>Почта:</strong></abbr> orders@teelab.ru collaboration@teelab.ru
                </div>

              </div>

            </div>

            <div class="col_one_third">

              <div class="widget widget_links clearfix">

                

                <ul>
                  <li><%= link_to 'О нас', support_aboutus_path %></li>
                  <li><%= link_to 'Ценовая политика', support_pricing_path %></li>
                  <li><%= link_to 'Оферта', support_offer_path %></li>
                  <li><%= link_to 'Контакты', support_contact_path %></li>
                  <li><%= link_to 'Помощь', support_help_path %></li>
                </ul>

              </div>

            </div>


          </div>

          <div class="col_one_third col_last">

            <div class="widget clearfix" style="margin-bottom: -20px;">

              <div class="row">

                <div class="col-md-6 bottommargin-sm">
                  <div class="counter counter-small"><span data-from="50" data-to="1506" data-refresh-interval="80" data-speed="3000" data-comma="true"></span></div>
                  <h5 class="nobottommargin">Продано товаров</h5>
                </div>

                <div class="col-md-6 bottommargin-sm">
                  <div class="counter counter-small"><span data-from="100" data-to="184" data-refresh-interval="50" data-speed="2000" data-comma="true"></span></div>
                  <h5 class="nobottommargin">Создано кампаний</h5>
                </div>

              </div>

            </div>

            

            <div class="widget clearfix" style="margin-bottom: -20px;">

              <div class="row">

                <div class="col-md-6 clearfix bottommargin-sm">
                  <a href="#" class="social-icon si-dark si-colored si-facebook nobottommargin" style="margin-right: 10px;">
                    <i class="icon-facebook"></i>
                    <i class="icon-facebook"></i>
                  </a>

                </div>
                <div class="col-md-6 clearfix">
                  <a href="https://www.instagram.com/teelab.ru/" class="social-icon si-dark si-colored si-rss nobottommargin" style="margin-right: 10px;">
                    <i class="icon-instagram"></i>
                    <i class="icon-instagram"></i>
                  </a>
                 
                </div>

              </div>

            </div>

          </div>

        </div><!-- .footer-widgets-wrap end -->

      </div>

      <!-- Copyrights
      ============================================= -->
      <div id="copyrights">

        <div class="container clearfix">

          <div class="col_half">
            Teelab.ru © 2017<br>
           
          </div>

          
          
          </div>



      </div><!-- #copyrights end -->

    </footer><!-- #footer end -->

app/views/layouts/_header.html.erb
    <!-- Header
    ============================================= -->
    <header id="header" class="full-header">

      <div id="header-wrap">

        <div class="container clearfix">

          <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

          <!-- Logo
          ============================================= -->
          <div id="logo">
            <%= link_to root_path, class: "standard-logo" do %><%= image_tag 'logo_n.png', alt: "Canvas Logo" %><% end %>
            <%= link_to root_path, class: "retina-logo" do %><%= image_tag 'logo@2x.png', alt: "Canvas Logo" %><% end %>
          </div><!-- #logo end -->

          <!-- Primary Navigation
          ============================================= -->
          <nav id="primary-menu">

            <ul>
              <li><%=link_to root_path do %><div>Главная</div><% end %>
              </li>
              <li><%=link_to support_aboutus_path do %><div>О нас</div><% end %>
              </li>
 
                <%if signed_in?%>
                  <li class="mega-menu"><%=link_to current_user.try(:email), edit_user_registration_path%></li>
                  <li class="mega-menu"><%=link_to "Выйти", destroy_user_session_path, method: :delete%></li>
                <%else%>
                  <li class="mega-menu"><%=link_to "Регистрация", new_user_registration_path%></li>
                  <li class="mega-menu"><%=link_to "Войти", new_user_session_path%></li>
                <%end%>
              
            </ul>

            <!-- Top Cart
            ============================================= -->
            <div id="top-cart">
              <a id="top-cart-trigger"  style="cursor: pointer;"><i class="icon-shopping-cart"></i><span id="cart_count"><%=@cart.total_count%></span></a>
              <div class="top-cart-content">
                <div class="top-cart-title">
                  <h4>Корзина Заказов</h4>
                </div>
                <div class="top-cart-items" id="cart-items">
                 <% @cart.line_items.each do |line_item| %>
                  <div class="top-cart-item clearfix">

                    <div class="top-cart-item-image">
                      <a href="#"><%= image_tag line_item.product.images.first.photo(:thumb) %></a>
                    </div>
                    
                    <div class="top-cart-item-desc">
                      <a href="#"><%= line_item.product.title %></a>
                      <span class="top-cart-item-price"><%= line_item.size.name %><br><%= line_item.total_price %> руб.</span>
                      <span class="top-cart-item-quantity">x <%= line_item.total_count %><br><br><%= link_to line_item_path(line_item.id), :method => :delete,  remote:true, class: "remove" do %><i class="icon-trash2"></i><% end %></span>
                    </div>

                  </div>
                   <% end %> 
                </div>
                <div class="top-cart-action clearfix">
                  <span class="fleft top-checkout-price" id="cart-total"><%= @cart.total_price %> руб.</span>
                  <%= link_to new_order_path, class: "button button-3d button-small nomargin fright" do %>Оформить <% end %>
                </div>
              </div>
            </div><!-- #top-cart end -->

            <!-- Top Search
            ============================================= -->
            <div id="top-search">
              <a href="#" id="top-search-trigger"><i class="icon-search3"></i><i class="icon-line-cross"></i></a>
              <form action="search.html" method="get">
                <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter..">
              </form>
            </div><!-- #top-search end -->

          </nav><!-- #primary-menu end -->

        </div>

      </div>

    </header><!-- #header end -->    




 




 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Teelab" %></title>
    <%= csrf_meta_tags %>
    
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PRWM7CD');</script>
    <!-- End Google Tag Manager -->

    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <script src="https://widget.cloudpayments.ru/bundles/cloudpayments"></script>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>



    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="stretched">



        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PRWM7CD"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->

    <!-- Document Wrapper
    ============================================= -->
    <div id="wrapper" class="clearfix">



        <%= render "layouts/header" %>

        <%= render "layouts/alerts" %>

        
          
          <%= yield %>



        <%= render "layouts/footer" %>

    </div><!-- #wrapper end -->
    <!-- Go To Top
    ============================================= -->
    <div id="gotoTop" class="icon-angle-up"></div>

    <%= javascript_include_tag "functions", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "plugins", 'data-turbolinks-track' => true %>

  </body>
   
</html>

app/views/layouts/landdev.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <%= display_meta_tags site: 'teelab.ru' %>

    <title><%= content_for?(:title) ? yield(:title) : "Teelab.ru" %></title>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PRWM7CD');</script>
    <!-- End Google Tag Manager -->



    <script src="https://widget.cloudpayments.ru/bundles/cloudpayments"></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= google_webfonts_init({
      google: ['Playfair Display SC']
    }) %>

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PRWM7CD"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= render "layouts/alerts" %>

    
      
      <%= yield %>

  



  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <%= display_meta_tags site: 'teelab.ru' %>

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PRWM7CD');</script>
    <!-- End Google Tag Manager -->

    <script src="https://widget.cloudpayments.ru/bundles/cloudpayments"></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PRWM7CD"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= render "layouts/alerts" %>

    
      
      <%= yield %>

  

    <%= render "layouts/footer" %>


  </body>
</html>

app/views/layouts/old_mailer_1481126406.html.erb
<html>
  <body>
    <%= yield %>
  </body>
</html>